### ISSUE TITLE
Add some python programs 

### ISSUE THREAD

**Issue by Astrodevil** [Astrodevil/Programming-Basics#10]
Always put question above code before commit in respective folders/files, So that anyone can understand
**Raise a New Issue So that I can assign it you**

**Comment by abhishekkumar11724** [comment]
hey! 👋
I was looking through the repo and I would like to contribute to this repo. So, could you explain me:- 
1. can we add any question solved in python?
2. can we add projects made in python?
3. and how many contributions can we make in one repo for hacktober.

**Comment by Aryan779** [comment]
Hey! @Astrodevil  I have made a jupyter file on Basics of python. Can I add that?

**Comment by Astrodevil** [comment]
> 
> 
> Hey! @Astrodevil I have made a jupyter file on Basics of python. Can I add that?

You can add any code and resources related to programming language, as this repo is for that. Just make sure your files need to be in correct folder and name it accordingly.  you can also make folder to add files related to your contents.

**Example**: 
 1. If you want to add simple program in python folder name it as xyz.py.
 2. If you want to add resources/projects related to python then make a new folder inside Python folder and add files                accordingly.

**Comment by Astrodevil** [comment]
@abhishekkumar11724 

**1. can we add any question solved in python?**
       Yes, Just make sure to add question along with code for better understanding.
**2. can we add projects made in python?**
       Yes, but make a separate project folder and add your project there. 
**3. and how many contributions can we make in one repo for hacktober.**
       You need 4 PR successfully merged for hactoberfest.

**Comment by Astrodevil** [comment]
Please made PR From October 1 so that it can be counted Read [Faqs](https://hacktoberfest.digitalocean.com/faq)

**Comment by ManasviGoyal** [comment]
Hi. Do I need to raise an issue before adding the file or I can do without that?

**Comment by Astrodevil** [comment]
> 
> 
> Hi. Do I need to raise an issue before adding the file or I can do without that?

Raising an issue is good thing, if your changes are not needed in this repo i can inform you.
So that you  instead can do changes that our repo needs.

You can do without that also, but give details about your addition/changes in Pull Request description. It would be helpful.

**Comment by ManasviGoyal** [comment]
> > Hi. Do I need to raise an issue before adding the file or I can do without that?
> 
> Raising an issue is good thing, if your changes are not needed in this repo i can inform you. So that you instead can do changes that our repo needs.
> 
> You can do without that also, but give details about your addition/changes in Pull Request description. It would be helpful.

Okay. I need to add a project. Can I do that?

**Comment by Astrodevil** [comment]
@ManasviGoyal yes but add a project folder if not added then add project.
So that other projects can also v added.

Put your whole project file in one folder

**Comment by ManasviGoyal** [comment]
> @ManasviGoyal yes but add a project folder if not added then add project. So that other projects can also v added.
> 
> Put your whole project file in one folder

When does the hacktoberfest start? At what time exactly?
Also can I make multiple PR to the same project?

**Comment by Astrodevil** [comment]
> 
> 
> > @ManasviGoyal yes but add a project folder if not added then add project. So that other projects can also v added.
> > Put your whole project file in one folder
> 
> When does the hacktoberfest start? At what time exactly? Also can I make multiple PR to the same project?

Yes, You can made multiple PRs in same project. Hactoberfest starts from October 1st [Read more](https://hacktoberfest.digitalocean.com/faq)

**Comment by dmytrohavrysh** [comment]
Hi!
I also want to add some code for Python.

**Comment by Astrodevil** [comment]
Go ahead👍🏻 @dmytrohavrysh

**Comment by ManasviGoyal** [comment]
Hi. Any idea when exactly the event starts? Has it started already? Little confused due to different timezones

**Comment by dmytrohavrysh** [comment]
> Go ahead👍🏻 @dmytrohavrysh

Should I be a contributor to make a PR?

**Comment by Astrodevil** [comment]
> 
> 
> Hi. Any idea when exactly the event starts? Has it started already? Little confused due to different timezones

Hacktoberfest Will Start from October 1st. It's not Started yet.

**Comment by Astrodevil** [comment]
> 
> 
> > Go ahead👍🏻 @dmytrohavrysh
> 
> Should I be a contributor to make a PR?

Yes! Are you asking about Hacktoberfest Registration options?

**Comment by dmytrohavrysh** [comment]
> > > Go ahead👍🏻 @dmytrohavrysh
> > 
> > 
> > Should I be a contributor to make a PR?
> 
> Yes! Are you asking about Hacktoberfest Registration options?

Yep!

**Comment by nitin30kumar** [comment]
Hello
I want to contribute some python codes to this repo. Can you suggest to me which kind of programs you need here like pattern, menu-driven, automation, etc?

**Comment by nitin30kumar** [comment]
> > Hello I want to contribute some python codes to this repo. Can you suggest to me which kind of programs you need here like pattern, menu-driven, automation, etc?
> 
> As this repo is made with a motive to help beginners to learn programming, So every kind of codes are welcomed. If necessaary add folder inside Python and contribute. **Raise new issue first**

Raised a new issue [here](https://github.com/Astrodevil/Programming-Basics/issues/40#issue-1012331464). Kindly do the needful.
