### ISSUE TITLE
I want to add some programs for Array Implementation and Operations in C Language.

### ISSUE THREAD

**Issue by Devesh225** [Astrodevil/Programming-Basics#104]
Array is a very useful data structure which is used almost everywhere. I would like to write properly documented Array ADT code, along with the operations we can do with Arrays, to make a good template for someone who wants to learn and utilize arrays.

Creating, Deleting, Inserting Elements, Merging Two Arrays, and much more along with the Time Complexities.

**Comment by Astrodevil** [comment]
Its already handled by someone here #98
