### ISSUE TITLE
I want to add a tic tac toe game based on minimax algorithm using c++ and concepts of dsa

### ISSUE THREAD

**Issue by Amulya77** [Astrodevil/Programming-Basics#105]
I want to add a  Game i.e. cpp code based on minimax algorithm

**Comment by Astrodevil** [comment]
@Amulya77 Go ahead put it in proper folder of this repo.

**Comment by Astrodevil** [comment]
@Amulya77 Link PR here if made

**Comment by Amulya77** [comment]
> @Amulya77 Link PR here if made

@Astrodevil  I have made a PR please check it #286

**Comment by Amulya77** [comment]
> @Amulya77 Link PR here if made

#286  hope you approve it I have provided with a proper description and you can check my code working correctly
@Astrodevil
