### ISSUE TITLE
Python Script to extract phone no. and email address from a text file.

### ISSUE THREAD

**Issue by joshiaastha** [Astrodevil/Programming-Basics#116]
Being a part of Hacktoberfest, I'm planning to add a python script which can extract phone no. and email address from a text file.
**Problem Statement:**
Say you have the boring task of finding every phone number and email address in a comments section of a popular blog. If you manually scroll through the page, you might end up searching for a long time. But if you had a program that could search the text in your clipboard for phone numbers and email addresses, you could simply press ctrl-A to select all the text, press ctrl-C to copy it to a .txt file, and then run your program. It would fetch just the phone numbers and email addresses it finds and write them to another .txt file.

I would like to work on this.

**Comment by joshiaastha** [comment]
Could you please assign this issue to me?

**Comment by Astrodevil** [comment]
Put it in Project folder under python by making separate folder with project name. Also add setup,tools,docs related to it.
