### ISSUE TITLE
Sum of Elements of Linked List (C++)

### ISSUE THREAD

**Issue by prabhxjottsingh** [Astrodevil/Programming-Basics#120]
I cannot see any program for adding the data elements of linked list.
I want to contribute with the same using recursion as well as without recursion in the Basic DSA folder.
Can you assign this to me ??

**Comment by Astrodevil** [comment]
Go Ahead!

**Comment by prabhxjottsingh** [comment]
#169 can you please review this :)

**Comment by prabhxjottsingh** [comment]
#172 I have done the task assigned, hope you will review it soon, and merge if its okay, otherwise you can tell me the error, thanks in advance. :)
