### ISSUE TITLE
A discord stock bot 

### ISSUE THREAD

**Issue by rustzz-27** [Astrodevil/Programming-Basics#121]
**Is your feature request related to a problem? Please describe.**
I want to contribute a small project called discord stock bot written in python and makes use of discord API

**Describe the solution you'd like**
The bot would give live stock price update when requested, top 25 gainers

please consider this request under hacktoberfest 2021
Thank you

**Comment by Astrodevil** [comment]
@rustzz-27 Are You planning to add this in project folder under python?

**Comment by rustzz-27** [comment]
yes

**Comment by Astrodevil** [comment]
@rustzz-27 Go Ahead👍🏼 Put your project under 1 folder.

**Comment by rustzz-27** [comment]
meaning i should add this under Python/Projects/ ? or can I create a complete separate folder itself?

**Comment by rustzz-27** [comment]
I have made a PR pls review it

**Comment by Astrodevil** [comment]
> meaning i should add this under Python/Projects/ ? or can I create a complete separate folder itself?
> 
> @Astrodevil pls let me know
> 
> Thanks

Yes put you project folder under python/projects/your folder

**Comment by rustzz-27** [comment]
> > meaning i should add this under Python/Projects/ ? or can I create a complete separate folder itself?
> > @Astrodevil pls let me know
> > Thanks
> 
> Yes put you project folder under python/projects/your folder

actually I added inside the python folder not inside the projects
is it okay?

**Comment by Astrodevil** [comment]
Add inside projects, all projects must be in 1 folder as you can see more projects are already there

**Comment by rustzz-27** [comment]
> Add inside projects, all projects must be in 1 folder as you can see more projects are already there

okaay will do that

**Comment by rustzz-27** [comment]
> Add inside projects, all projects must be in 1 folder as you can see more projects are already there

Done

**Comment by Astrodevil** [comment]
> 
> 
> > Add inside projects, all projects must be in 1 folder as you can see more projects are already there
> 
> Done

provide reference of that PR or mention this issue in that PR.

**Comment by rustzz-27** [comment]
> > > Add inside projects, all projects must be in 1 folder as you can see more projects are already there
> > 
> > 
> > Done
> 
> provide reference of that PR or mention this issue in that PR.

#135
