### ISSUE TITLE
want to add a tic tac toe program in python

### ISSUE THREAD

**Issue by abhishekkumar11724** [Astrodevil/Programming-Basics#129]
I was wondering that since its a Beginner programmer guide, so shouldn't it contain some beginner friendly games.

so I want to add a tic tac toe game which I had written in python. 

its a beginner friendly and easy to understand program and a really helpful to the new programmers to understand the logics.

so please assign this request to me.

**Comment by Astrodevil** [comment]
@abhishekkumar11724 its already done by someone.
