### ISSUE TITLE
To add binary tree algorithms in the repository

### ISSUE THREAD

**Issue by The-An0rack** [Astrodevil/Programming-Basics#130]
I would like to add binary tree algorithms such as traversal algorithms(in order, pre-order, post order, level order, etc.) and several other algorithms which are must be known for coding interviews.

Location: DSA/DSA-CPP

**Comment by Astrodevil** [comment]
Please see PR #95 and Let me know if you are adding some more and different programs by making proper folder. Then i will assign this to you.

**Comment by The-An0rack** [comment]
The mentioned issue only implements limited operations in a BST(binary search tree) such as insertion, deletion, searching, printing in-order type, while I am proposing to implement binary tree and its important algorithms in C++.

**Comment by Astrodevil** [comment]
@The-An0rack Good to go, follow proper folder order

**Comment by Astrodevil** [comment]
Link PR here if made
