### ISSUE TITLE
card game in python

### ISSUE THREAD

**Issue by abhishekkumar11724** [Astrodevil/Programming-Basics#131]
I want to add a card game which is written in python. its a terminal based game and I made it to show oops concept in python and its good for the beginners if they want to learn work flow. so please assign this issue to me.

**Comment by Astrodevil** [comment]
@abhishekkumar11724 Go Ahead! Put you game in Python/Games folder

**Comment by abhishekkumar11724** [comment]
sir I had completed the task, hoping you will review it soon.
