### ISSUE TITLE
black deck in python

### ISSUE THREAD

**Issue by abhishekkumar11724** [Astrodevil/Programming-Basics#134]
I want to contribute a game "black deck" made in python. its a terminal based game but its different from other games as its above the beginner friendly game. this game is for experts by which they can understand complex logics and even high use of oops.
this game is a two person game were one is user and other is pc that is why is really good for programmers who had learned oops and had gained command in python. so please assign this issue to me.

**Comment by Astrodevil** [comment]
#131 Is this the same?

**Comment by abhishekkumar11724** [comment]
no its not same. the difficulty level is expert.
it is require user inputs and the other one is just a stimulation on how a general card game works.

u can think of it as the next level.
and after this i am working on a GUI based card game in QT5.

**Comment by Astrodevil** [comment]
@abhishekkumar11724 Go ahead

**Comment by Astrodevil** [comment]
Link PR here if made

**Comment by abhishekkumar11724** [comment]
#228
