### ISSUE TITLE
I want to contribute in hacktoberfest

### ISSUE THREAD

**Issue by KshitizSharma11** [Astrodevil/Programming-Basics#14]
I would like to contribute some JAVA and C++ programs in this repository

**Comment by Astrodevil** [comment]
please edit the description and mention what you want to change or add in this repository

**Comment by KshitizSharma11** [comment]
> @KshitizSharma11 please edit the description and mention what you want to change or add in this repository

I added the description.

**Comment by Astrodevil** [comment]
yea sure go ahead

**Comment by sunnybhagwat35** [comment]
Hi, I'm a beginner at contributing to open source. I would like to start with this if it's Ok.
I would like to contribute some DataStructres in JAVA  programs to this repository.

**Comment by Astrodevil** [comment]
> 
> 
> Hi, I'm a beginner at contributing to open source. I would like to start with this if it's Ok. I would like to contribute some DataStructres in JAVA programs to this repository.

Ok, But raise a new issue. You have to put Java data structures into DSA folder>DSA-Java
