### ISSUE TITLE
Bubble Sort in Java

### ISSUE THREAD

**Issue by dmytrohavrysh** [Astrodevil/Programming-Basics#140]
I would to add a Bubble Sort in Java. It will be very useful for newbies.

**Comment by Astrodevil** [comment]
> 
> 
> I would to add a Bubble Sort in Java. It will be very useful for newbies.

Put it in DSA/DSA-Java/Sorting-Algo/..    folder.

**Comment by Astrodevil** [comment]
#143 #144 Also solve this issue in 1 Pr and  Link PR here if made
