### ISSUE TITLE
ADD Python project - Youtube Video downloader

### ISSUE THREAD

**Issue by nightfury-crypto** [Astrodevil/Programming-Basics#141]
I have a youtube video downloader project. 
it is gui based made using tkinter module. I want to add it in your repo.  

![image](https://user-images.githubusercontent.com/65121678/135583424-8384619a-14cb-4918-aaa2-a819552d42bd.png)

**Comment by Astrodevil** [comment]
Put it in Python/Projects/Your project name folder. with proper docs and setup instructions
