### ISSUE TITLE
ADD Python Project - todo app

### ISSUE THREAD

**Issue by nightfury-crypto** [Astrodevil/Programming-Basics#145]
todo app made using tkinter module. It is gui based and you can add and delete the items.

![image](https://user-images.githubusercontent.com/65121678/135584355-6b0b90cc-d22c-4e66-bf0b-becaa666deab.png)

**Comment by Astrodevil** [comment]
Go ahead👍🏼

**Comment by Astrodevil** [comment]
Link PR here if made
