### ISSUE TITLE
Adding python program.py

### ISSUE THREAD

**Issue by DipanshuKumarRai** [Astrodevil/Programming-Basics#146]
i want to add Simple Calculator by Using Functions in python folder

**Comment by Astrodevil** [comment]
👍🏼

**Comment by SCI-COPATH** [comment]
can you assigned to me ?

**Comment by SCI-COPATH** [comment]
@DipanshuKumarRai 
can you assigned to me ?

**Comment by Astrodevil** [comment]
> 
> 
> can you assigned to me ?

its already assigned. if you want to raise a Pr please create new issue and provide details there

**Comment by Astrodevil** [comment]
@DipanshuKumarRai Link PR here if made
