### ISSUE TITLE
ADD Python project - Calculator 

### ISSUE THREAD

**Issue by nightfury-crypto** [Astrodevil/Programming-Basics#147]
gui based calculator made using tkinter module.

it is a simple calculator with view history result feature.

![image](https://user-images.githubusercontent.com/65121678/135584729-6fd990fc-6692-4a27-80a1-fe1250d6f1ea.png)

**Comment by Astrodevil** [comment]
go ahead

**Comment by Astrodevil** [comment]
Link PR here if made

**Comment by nightfury-crypto** [comment]
> Link PR here if made

#234
