### ISSUE TITLE
Landing Page For programming-basics

### ISSUE THREAD

**Issue by Astrodevil** [Astrodevil/Programming-Basics#15]
**Having a proper landing page to show all contents from this repo**

*More Suggestions Welcomed*🙏🏼

Can You Make Like this? https://sushreesatarupa.github.io/DSA-cpp-Hacktoberfest2021/

Or You can Make whole landing page for viewing everything from repo.

**Comment by HimadriPathak** [comment]
I can help but I need to know want all things you want in that page

**Comment by Astrodevil** [comment]
@HimadriPathak drop your ideas.🤔

**Comment by ssahibsingh** [comment]
I have made similar looking site of what you have given example.

**Comment by Astrodevil** [comment]
Anyone Interested to Work on documentation part? please reply

**Comment by ssahibsingh** [comment]
@Astrodevil Do I have to raise another issue or you will assign this one to me?

**Comment by HimadriPathak** [comment]
we can add a background as the hacktoberfest website and all the contents in a grid like manner and centre aligned.

and I can also help with documentation work.

**Comment by Astrodevil** [comment]
@HimadriPathak No hacktoberfet background needed, needs random attractive backgrounds. may be this project can be added to different open source programs, so section for that will be needed.

**Comment by Astrodevil** [comment]
@ssahibsingh Please Make a Pr and mention here, no need to create issue.


@HimadriPathak Please wait! let him make 1 PR, then you can work on documentation  and Enhancement.

**Comment by ssahibsingh** [comment]
@Astrodevil I have made a new PR but I don't know how this PR gets added to my previous PR of "Added Pattern Programs". If you can do something please make it correct.

**Comment by Astrodevil** [comment]
See This: https://astrodevil.github.io/Programming-Basics/

You have to put html file on front(outside every folder).and add valuable contributors section by copying code of README file. go and check it.

**Comment by Astrodevil** [comment]
> 
> 
> @Astrodevil I have made a new PR but I don't know how this PR gets added to my previous PR of "Added Pattern Programs". If you can do something please make it correct.

mention PR no. or Issue by using (#no. ) from title

**Comment by ssahibsingh** [comment]
Issue no. #19 and PR no. #159

**Comment by Astrodevil** [comment]
> 
> 
> See This: https://astrodevil.github.io/Programming-Basics/
> 
> You have to put html file on front(outside every folder).and add valuable contributors section by copying code from bottom of project README file. go and check it.

@ssahibsingh make these changes then i will merge it

**Comment by Astrodevil** [comment]
@HimadriPathak Now You can work on more enhancement of landing page. 

Add more custom documentation 
Made a section to mention/show if this program is participating in other open source programs  other than hacktoberfest

**Comment by tausiq2003** [comment]
@Astrodevil can I modify some programs for efficiency

**Comment by tausiq2003** [comment]
@Astrodevil add label `hacktoberfest` you have added `Hacktoberfest`

**Comment by tausiq2003** [comment]
please reply can I do this?

**Comment by HimadriPathak** [comment]
> @HimadriPathak Now You can work on more enhancement of landing page. updated page: https://astrodevil.github.io/Programming-Basics/ Add more custom documentation Made a section to mention/show if this repository is participating in other open source programs other than hacktoberfest.
> 
> In footer don't remove credit (developed by) just add you name there.

OK I will work on it tomorrow
