### ISSUE TITLE
ADD Python project - LOGIN FORM

### ISSUE THREAD

**Issue by nightfury-crypto** [Astrodevil/Programming-Basics#155]
gui based login form. 

username = user123
password = password@123

![image](https://user-images.githubusercontent.com/65121678/135593616-55e84b84-4b84-4186-ac99-6563a544cdd6.png)

**Comment by Astrodevil** [comment]
Link PR here if made

**Comment by nightfury-crypto** [comment]
> Link PR here if made

#234
