### ISSUE TITLE
Add a C++ program that converts any string to its Binary form.

### ISSUE THREAD

**Issue by arpitbaheti2002** [Astrodevil/Programming-Basics#156]
This is an interesting project I did as a beginner that allows users to enter a string. and then displays it in Binary format.
I like converting my name in binary to know how the computer actually reads it.

**Comment by Astrodevil** [comment]
Please provide details about in which folder are you going to put this or are you adding any folder. you mentioned  project

**Comment by arpitbaheti2002** [comment]
I would like to add it to Programming-Basics/C++/ where all basic C++ programs are stored. Thank you for your response.

**Comment by Astrodevil** [comment]
Ok Good to go.

**Comment by arpitbaheti2002** [comment]
I have made pull request #112 for this feature. Please review it. Thank you for this opportunity.

**Comment by Siddhesh4501** [comment]
can i get assigned for this one?
