### ISSUE TITLE
python based GUI calculator

### ISSUE THREAD

**Issue by abhishekkumar11724** [Astrodevil/Programming-Basics#162]
I want to add a **QT5** based GUI calculator which is written in python. its is a good starter project for those who want to learn GUI.
so please assign me this task.
![image](https://user-images.githubusercontent.com/82565067/135612315-a37db54c-63c4-46ee-bda9-4b8af639103c.png)

**Comment by Astrodevil** [comment]
Its already assigned in  #147

**Comment by abhishekkumar11724** [comment]
sir I had read about that and it was made in tkinter and mine is in QT5 which is a more versatile and a broader than tkinter

**Comment by Astrodevil** [comment]
@abhishekkumar11724 Ok put proper details in the the project so that anyone can know.

**Comment by Astrodevil** [comment]
Link PR here if made

**Comment by abhishekkumar11724** [comment]
#271
