### ISSUE TITLE
Adding to the DSA community classroom

### ISSUE THREAD

**Issue by ShouryaBrahmastra** [Astrodevil/Programming-Basics#163]
Would like to work on these problems (My preferred language is C ).

1 Input a year and find whether it is a leap year or not.

2 Take two numbers and print the sum of both.

3 Take a number as input and print the multiplication table for it.

4 Take a 2 numbers as inputs and find their HCF and LCM.

5 Keep taking numbers as inputs till the user enters ‘x’, after that print sum of all.

Please assign me this task

**Comment by Astrodevil** [comment]
Dsa community Classroom folder is for java problems being taught in a course

You can add questions and programms in C folder
