### ISSUE TITLE
I want to add some Python Programs

### ISSUE THREAD

**Issue by kahtras665** [Astrodevil/Programming-Basics#17]
**Hey! @Astrodevil**
I would like to contribute to this repository by adding some cool Python Programs!

**Comment by Astrodevil** [comment]
Go ahead👍🏼

**Comment by kahtras665** [comment]
> Go ahead👍🏼
> 
> But wait till October 1 if you want your PR to be Eligible for hacktoberfest 

Thank you so much for the information!
I will do the PR on 1st October!

**Comment by kahtras665** [comment]
Hey! @Astrodevil
I just saw that the label you've added is **'hactoberfest'**.
It should be **'hacktoberfest'** for a successful PR.

**Comment by Astrodevil** [comment]
Yeah, you noticed it Thanks🙌🏼 but no issue PR lebel is correct

**Comment by kahtras665** [comment]
Hey @Astrodevil
I've done a PR, could you please merge it with the main repository. 
#110
