### ISSUE TITLE
Finding the norm of a matrix using dynamic memory allocation

### ISSUE THREAD

**Issue by ShouryaBrahmastra** [Astrodevil/Programming-Basics#177]
Would like do this using c 
Can you please assign this

**Comment by Astrodevil** [comment]
You have to make appropriate folder or choose proper directory to put this program of C

**Comment by Astrodevil** [comment]
Link PR if made

**Comment by ShouryaBrahmastra** [comment]
https://github.com/Astrodevil/Programming-Basics/pull/289
Here it is sorry for the delay
