### ISSUE TITLE
Programs on matrices

### ISSUE THREAD

**Issue by tanmayck1201** [Astrodevil/Programming-Basics#191]
Hello @Astrodevil, i checked the repo about matrices programs but didn't found any!
I can add some of the matrices pgms like Diagonal, lower triangular matrix, etc... implementaion in cpp language.  
Kindly assign this task to me, will complete at the earliest! #Hacktoberfest2021

**Comment by sushant-sinha** [comment]
Hi @tanmayck1201, I wrote a program in java for inverting a matrix #202 . Please let me know other programs that you will be making in cpp so that I can implement those in java.

**Comment by Astrodevil** [comment]
@sushant-sinha raise new issue and get it assigned before making PR

**Comment by sushant-sinha** [comment]
Hi @Astrodevil, I raised a new issue #235 . Sorry for the inconvenience caused.

**Comment by Anjani87** [comment]
please assigne me this issue i can solve this is issue accordingly i am a good programmer in c language and recently i am pursuing b tech in computer science engeneering branch . (2 year)

**Comment by Astrodevil** [comment]
@Anjani87 raise new issue and mention what you want to work on, i will assign that

**Comment by Anjani87** [comment]
YOU CAN GIVE ANY ISSUE IN C LANGUAGE I CAN SOLVE IT. AND WILL TRY MY BEST
