### ISSUE TITLE
Factorial Function

### ISSUE THREAD

**Issue by imsamimalik** [Astrodevil/Programming-Basics#193]
I see that there is a factorial Function snippet but it's messy. I've a really neat Factorial function using Recursion.

**Comment by imsamimalik** [comment]
Time complexity of my snippet is O(n).

**Comment by Anjani87** [comment]
please assigne me this issue i can solve this is issue accordingly i am a good programmer in python language and recently i am pursuing b tech in computer science engeneering branch . (2 year) AND I HAVE RECENTLY COMPLETED A PAID TRAINNING COURSE FROM HACKERRANK IN PYTHON.

**Comment by Anjani87** [comment]
please assigne me this issue i can solve this is issue accordingly i am a good programmer IN C language and recently i am pursuing b tech in computer science engeneering branch . (2 year)

**Comment by imsamimalik** [comment]
Sorry. I've solved it and created pull request.

**Comment by tausiq2003** [comment]
I will do it

**Comment by tausiq2003** [comment]
i have worked on it please close this issue or find bugs.

**Comment by imsamimalik** [comment]
I've already purposed the lull request before you all. This issue is just an placeholder for that pull request.

**Comment by Astrodevil** [comment]
@imsamimalik Mention your PR here

**Comment by imsamimalik** [comment]
PR #193
