### ISSUE TITLE
Calculator GUI in Java

### ISSUE THREAD

**Issue by rajan1199** [Astrodevil/Programming-Basics#217]
In which folder can I add calculator GUI made in Java?

**Comment by rajan1199** [comment]
Hey! Assign this to me.

**Comment by Astrodevil** [comment]
Made a new folder "projects" inside Java Directory and put it there in a folder

**Comment by rajan1199** [comment]
I have added the calculator GUI (Pull request 315).

**Comment by rajan1199** [comment]
#315
