### ISSUE TITLE
Heapsort in Java

### ISSUE THREAD

**Issue by esheetaparulekar** [Astrodevil/Programming-Basics#219]
Hello, I would like to add Java code for Heapsort in DSA->SortingAlgo. Could you please assign me this issue?

**Comment by Astrodevil** [comment]
Check DSA/DSA-Java folder, its already there. Please let me know.

**Comment by esheetaparulekar** [comment]
> Check DSA/DSA-Java folder, its already there. Please let me know.

No, it's not there in the DSA/DSA-JAVA folders.

**Comment by Astrodevil** [comment]
Ok, Go ahead  put it inside proper directory or create a  folder of Sorting Algo inside DSA-Java
