### ISSUE TITLE
Password Generator Utility in Python

### ISSUE THREAD

**Issue by siphyshu** [Astrodevil/Programming-Basics#223]
Hi! I'd like to create a "Utility" folder under Python/ which would include useful and interesting python programs.

To start - I want to contribute a simple password generator script to suggest passwords.

![password-gen-output](https://user-images.githubusercontent.com/52672162/135708438-4fdf634e-50ef-4ab8-9374-7e38c44bda09.png)

**Comment by subh-chaturvedi** [comment]
@Astrodevil take a look and review.

**Comment by Astrodevil** [comment]
@siphyshu Is this a project, then project folder is already there in python? please explain about adding a 'Utility' folder. what types of python contents will go in this folder?

**Comment by siphyshu** [comment]
This cannot really be classified as a project in my opinion. A Utility folder will contain more or less standalone python scripts that aren't projects but just useful programs that may help you in any way, such as - A Password Generator, A File Sorter, Perhaps a Currency Convertor, A Base64 (or Morse Code!) Encode-Decode Tool, etc. I hope I get my point accross.

If you want I can just add the above programs under the Projects folder nevertheless. @Astrodevil ^^

**Comment by Astrodevil** [comment]
Ah!Ok add utility folder as you mentioned earlier and also attach a readme adding this explanation

**Comment by siphyshu** [comment]
Thanks! Sure, I'll do that, and yeah this is for hacktoberfest.
Would be nice if you could add the label for the same. 🤗
