### ISSUE TITLE
Want to add more useful and descriptive C++ codes

### ISSUE THREAD

**Issue by devanshtivari** [Astrodevil/Programming-Basics#23]
Being a C++ developer I would request you to allow me to add some more codes into your repository to make it even more comprehensive.

**Comment by Astrodevil** [comment]
Go Ahead🎈

**Comment by LikhithaTadikonda** [comment]
Even I want to contribute too.

**Comment by subh-chaturvedi** [comment]
@LikhithaTadikonda Make a new issue with more specific title on the kind of code you wish to add, and then make a PR referencing that issue.
