### ISSUE TITLE
Diamond Number pattern in cpp

### ISSUE THREAD

**Issue by prakhar3062** [Astrodevil/Programming-Basics#254]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tausiq2003** [comment]
![image](https://user-images.githubusercontent.com/80088029/135726075-40ded037-cbb1-4432-bcce-f30a154b23c0.png)
Wait I am working on this

**Comment by tausiq2003** [comment]
I will solve in C language wait...

**Comment by tausiq2003** [comment]
i have worked on it please close this issue or find bugs.
