### ISSUE TITLE
Add Pascal's Trianlge Pattern in pattern folder (C++)

### ISSUE THREAD

**Issue by prabhxjottsingh** [Astrodevil/Programming-Basics#260]
I want to add a C++ program that prints, this Pascal's triangle pattern in the pattern folder of C++ language.
                1
            1      1
         1      2      1
      1      3      3      1
Please assign me this issue. :)

**Comment by esheetaparulekar** [comment]
Can I work on this issue in Java?

**Comment by bsen20** [comment]
Can I work on this in cpp with different approaches

**Comment by Astrodevil** [comment]
> 
> 
> Can I work on this issue in Java?

@esheetaparulekar Yes You can, make new folder "Pattern" under Java and put inside it, also move other pattern program of java inside that folder

**Comment by prabhxjottsingh** [comment]
#293 Completed this one, hope you will review it soon. :)
