### ISSUE TITLE
Diamond pattern for N rows in CPP

### ISSUE THREAD

**Issue by Yogesh733** [Astrodevil/Programming-Basics#265]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tausiq2003** [comment]
wait working on it

**Comment by tausiq2003** [comment]
i have worked on it please close this issue or find bugs.

**Comment by Yogesh733** [comment]
I can try to fix out the bugs in your code

**Comment by tausiq2003** [comment]
Wait will I fix that

**Comment by tausiq2003** [comment]
Yeah you can

**Comment by tausiq2003** [comment]
May I know the bugs.

**Comment by tausiq2003** [comment]
😊

**Comment by Meghwantsingh** [comment]
I like to do this problem Can I.
