### ISSUE TITLE
The Curious Case Of Benjamin Bulbs

### ISSUE THREAD

**Issue by KhafiaAyyub** [Astrodevil/Programming-Basics#267]
Description: 
As it is a basic question of programming ,the issue will cover the solution to `The Curious Case Of Benjamin Bulbs` problem in JAVA.

**Comment by KhafiaAyyub** [comment]
can i work on this issue?

**Comment by Astrodevil** [comment]
Please explain in which directory are you planning to put this java problem, or need to create new folder

**Comment by KhafiaAyyub** [comment]
> Please explain in which directory are you planning to put this java problem, or need to create new folder

I would like to add in [Programming-Basics/Java](https://github.com/Astrodevil/Programming-Basics/tree/main/Java)

**Comment by Astrodevil** [comment]
Is this a DSA based question then put it in DSA/DSA-Java/Questions... comment out the whole concept in code
