### ISSUE TITLE
MultiplicationTable.cpp

### ISSUE THREAD

**Issue by arpitbaheti2002** [Astrodevil/Programming-Basics#287]
### Description:
I would like to add a **C++ program** that displays the multiplication table of any given integer in a very clear and spacious format.

### How it is different?
I would like to use the features of the <iomanip> library to provide output in a more neat and clear format to the user.

### Programming Language used:
- C++

### Concepts Used:
- Basic input / output.
- Arithmetic operators.
- Loop.

### Location:
Astrodevil/Programming-Basics/C++

### Sample Input:
4

### Sample Output:
4   *   1   =    4
4   *   2   =    8 
.
.
.
4   *  10 =  40

**Comment by ShouryaBrahmastra** [comment]
Would like you to please assign me this

**Comment by snehadaripa** [comment]
I would like to fix this issue. Please assign it to me.

**Comment by cyberskull99297** [comment]
Hii, I would like to contribute through this programme. I am a beginner at open source and this programme can boost my beginning. Please assign this issue to me.
