### ISSUE TITLE
Moving some files to different folder

### ISSUE THREAD

**Issue by Astrodevil** [Astrodevil/Programming-Basics#297]
You can move DSA based C programming files to DSA/DSA-C/.... by making appropriate folder. That will be helpful if we differentiate DSA problems from others.

**Comment by wisdomkhan** [comment]
I would like to work on the issue.

**Comment by Astrodevil** [comment]
Go Ahead!

**Comment by wisdomkhan** [comment]
May I also move the 'Sorting Algorithm' (implemented in cpp) to DSA-CPP?

**Comment by Astrodevil** [comment]
Yes, You can also arrange more folders of DSA

**Comment by wisdomkhan** [comment]
I have created a PR. Please merge it and I hope you'd add the required Hacktoberfest tags. Thank you!

**Comment by wisdomkhan** [comment]
Sure. I didn't understand what do you want me to do with the game folder.

**Comment by wisdomkhan** [comment]
Rest I have done and started another PR.
