### ISSUE TITLE
Add new programming language (Javascript)

### ISSUE THREAD

**Issue by Koddi-Evangelista** [Astrodevil/Programming-Basics#302]
**Is your feature request related to a problem? Please describe.**
I see that there is no javascript resources in this repo and it would be a good idea to add it as a new programming language in this repo.

**Comment by Astrodevil** [comment]
Would love to add more resources. What you want to add in this repo related to javascript? Please let me know.

**Comment by Koddi-Evangelista** [comment]
> Would love to add more resources. What you want to add in this repo related to javascript? Please let me know.
> 
> If you want to work about this, I will Assign you

Yes you can assign me. I would like to contribute on the data structure and algorithm side of javascript..

**Comment by Astrodevil** [comment]
Go ahead! put it in Appropriate directory

**Comment by Astrodevil** [comment]
Please move all JavaScript DSA based resources to DSA/DSA-JavaScript... directory and leave this main JavaScript folder here for resources other than DSA.
