### ISSUE TITLE
Programs for C++ Stl. 

### ISSUE THREAD

**Issue by Geek-Tekina** [Astrodevil/Programming-Basics#31]
Can I add C++ stl programs, and will it be counted as 1 successful PR for hactoberfest 2021?

**Comment by Astrodevil** [comment]
@Geek-Tekina Yes, You can add stl programs, maybe you can create separate folder inside C++ for better understanding.

And PR created from October 1 will be counted as successful PR for hactoberfest 2021.

**Comment by Geek-Tekina** [comment]
Okay so I should start contribution from today or 1 of Oct?

**Comment by Astrodevil** [comment]
> 
> 
> Okay so I should start contribution from today or 1 of Oct?

You can contribute anytime,  
Oct 1 only for hactoberfest.

If you want to work on this I can assign you.

**Comment by Geek-Tekina** [comment]
You please assign me to this issue!

**Comment by Geek-Tekina** [comment]
Thank You. I will contribute to it as my first PR for hactoberfest 2021. I am a begineer sir. So guide me through the whole process please!

**Comment by Astrodevil** [comment]
Okh, Just put everything in order before commit, You can do good🙌🏼

**Comment by Geek-Tekina** [comment]
Okay sir Thank You.
Sir Confirm the steps pls.
1. Forking the repo.
2. Adding STL folder to C++.
3. adding programs.
4. Creating a pr for this issue.
5. I , Successfully completed my 1 pr for Hactoberfest .

**Comment by Astrodevil** [comment]
Yes! This is the right step. 🎯

**Comment by deenu-1001** [comment]
please assign this to me.

**Comment by Astrodevil** [comment]
> 
> 
> please assign this to me.

already assigned you can work on other issues.

**Comment by deenu-1001** [comment]
okay sir not a problem
