### ISSUE TITLE
Java data structures into DSA folder>DSA-Java

### ISSUE THREAD

**Issue by sunnybhagwat35** [Astrodevil/Programming-Basics#33]
Can I add Java data structures, and will it be counted as a successful PR  for Hacktoberfest 2021?

**Comment by sunnybhagwat35** [comment]
Thank you, It will be my 1st PR of Hacktoberfest 2021.

**Comment by sunnybhagwat35** [comment]
By the way, is it necessary to add a label as Hacktoberfest to the issue cuz this issue don't have that label

**Comment by Astrodevil** [comment]
> 
> 
> By the way, is it necessary to add a label as Hacktoberfest to the issue cuz this issue don't have that label
I will add them, If you make pr from oct1

**Comment by sunnybhagwat35** [comment]
Oh, Thank you
