### ISSUE TITLE
Enhance Landing Page

### ISSUE THREAD

**Issue by Astrodevil** [Astrodevil/Programming-Basics#344]
Please see all kinds of contents by visiting our repository. Make landing page clear and detailed, such that any beginner can see and take help by visiting repository through landing page. 

**Keep in Mind**
- All the contents in a grid like manner and center aligned.
- Put every file related to landing page in "*assets*" and *index.html* outside, same as now.
- Add more custom documentation.
- Made a section to mention/show if this repository is participating in other open source programs other than hacktoberfest.
- In footer don't remove credit (developed by) just add your name there.
- **Add Support Button. paste this script** (  <script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
                data-id="Astrodevil" data-description="Support me on Buy me a coffee!" 
                data-message="" data-color="#40DCA5"
                data-position="Right"
                data-x_margin="50" data-y_margin="50">
            </script>  )

**Comment by nishantkumar1308** [comment]
please assign it to me

**Comment by Astrodevil** [comment]
Go Ahead @nishantkumar1308

**Comment by nishantkumar1308** [comment]
thanks for assign it to me @Astrodevil

**Comment by Astrodevil** [comment]
Also mention moto of this repo/project: (To Collect every resources and help beginners ) Add some documentations by yourself.

**Comment by Astrodevil** [comment]
Yes,

**Comment by nishantkumar1308** [comment]
![Screenshot (440)](https://user-images.githubusercontent.com/55284694/136682482-c16ea3ad-718d-4b13-ad2c-2a483edb930c.png)
Navbar is responsive and interactive  is it okay???

**Comment by Astrodevil** [comment]
looking Good.. but instead of adding just hacktoberfest banner we need a section **See Point 4** So that we can arrange/add small banners of more open source programs

**Comment by nishantkumar1308** [comment]
can i add description about Other opne souce like MLH etc

**Comment by nishantkumar1308** [comment]
ok I been little bit buzy ,I will do as early as possible

**Comment by nishantkumar1308** [comment]
@Astrodevil  what can i do now ?? please update my changes on live website.

**Comment by Astrodevil** [comment]
@nishantkumar1308 actually check your pr you have to move files of dynamic programming folder then I will merge it. Sorry for the delay, I am facing some Internet issue.

**Comment by nishantkumar1308** [comment]
@Astrodevil  when did i become valuable contributor??
😄
