### ISSUE TITLE
ATM

### ISSUE THREAD

**Issue by NEWCODECITY** [Astrodevil/Programming-Basics#356]
This program gives you a roughly idea about, how an ATM works. 
User will have to input the amount they want to retrieve and their current amount, then it will return you the remaining amount after the transaction and the bank charges.
If anything goes wrong, it will simply return the current amount.

**Comment by nishantkumar1308** [comment]
please assign it to me i will do in c++

**Comment by Astrodevil** [comment]
@NEWCODECITY Is this a project or just 1 program file.

**Comment by NEWCODECITY** [comment]
It's a program file only

**Comment by sai-sri-nandan** [comment]
Hey.. I would like to work on this.. Can you assign it to me? and give me more details?
