### ISSUE TITLE
Free-Resources Needed

### ISSUE THREAD

**Issue by Astrodevil** [Astrodevil/Programming-Basics#357]
Add some good Free resources to learn programing. Video links, E books, documentations,etc.

make proper markdown file to showcase it.For different programming languages make folders.

**Comment by Astrodevil** [comment]
yes, I am taking care of that while merging PR

**Comment by Astrodevil** [comment]
We can merge more small things needed in this Repo after hacktoberfest.

**Comment by nishantkumar1308** [comment]
@Astrodevil  ya, but first we have to take care that this repo is not excluded in hacktoberfest.
