### ISSUE TITLE
Armstrong number using python

### ISSUE THREAD

**Issue by kumarankm** [Astrodevil/Programming-Basics#368]
**Is your feature request related to a problem? Please describe.**
Yes, in python there are no features to display Armstrong number

**Describe the solution you'd like**
I would like to add algo to find Armstong numbers using python

**Describe alternatives you've considered**
I would like to give a solution in order of O(n)

**Additional context**
Nope, just a program.
Assign this issue under hacktoberfest

**Comment by Anjani87** [comment]
Please assign me this
