### ISSUE TITLE
Add a few unique programs into the C++ folder

### ISSUE THREAD

**Issue by prahuljose** [Astrodevil/Programming-Basics#38]

**Comment by Astrodevil** [comment]
@prahuljose please provide details about programs you want to contribute.

**Comment by prahuljose** [comment]
> @prahuljose please provide details about programs you want to contribute.

I plan to add:
1. Matrix Multiplication
2. Swapping 2 numbers w/o an extra variable
3. Reverse a given number (including leading '0' digit)

**Comment by Astrodevil** [comment]
@prahuljose Ok, you are good to go.
