### ISSUE TITLE
Add Some C++ files

### ISSUE THREAD

**Issue by Astrodevil** [Astrodevil/Programming-Basics#4]
Please add more codes, or questions along with solutions in [C++ folder](https://github.com/Astrodevil/Programming-Basics/tree/main/C%2B%2B)

**Raise a New Issue So that I can assign it you**

**Comment by Aayush0606** [comment]
Hey can I add some DSA problems in DSA-community classroom?

**Comment by Astrodevil** [comment]
Actually DSA-community classroom folder contains questions from a course, if you are doing the same course then go ahead.
Otherwise add dsa problems [here](https://github.com/Astrodevil/Programming-Basics/tree/main/DSA)

**Comment by Aayush0606** [comment]
Ok got it.One more question , if I submit a PR today will it be counted for hacktober fest!?

**Comment by Astrodevil** [comment]
It will be counted after the start of hactoberfest program

**Comment by Niyati3031** [comment]
@Astrodevil can you assign me this for Hacktoberfest 21

**Comment by Astrodevil** [comment]
> 
> 
> @Astrodevil can you assign me this for Hacktoberfest 21

Lots of contributions can be done on this issue, So raise a new issue regarding this, I will assign that to you.👍🏼

**Comment by Niyati3031** [comment]
> > @Astrodevil can you assign me this for Hacktoberfest 21
> 
> Lots of contributions can be done on this issue, So raise a new issue regarding this, I will assign that to you.👍🏼

If i create a new issue and work there will that add to Hacktoberfest 21
Or can i make a pr to this issue itself and it will add to Hacktoberfest 21
I am new so don't know how it works..

**Comment by Astrodevil** [comment]
@Niyati3031 Its better if you create PR during hactoberfest coding period, From October 1 so that it will be counted for the program. You can create issue anytime

**Comment by Aryan779** [comment]
@Astrodevil I have a made program on book store. Can I contribute it?

**Comment by Aryan779** [comment]
its in c++

**Comment by Aryan779** [comment]
@Astrodevil I have made a program on book store. It involves the use of single linked list. So can I contribute in c++ folder.

**Comment by Astrodevil** [comment]
> 
> 
> @Astrodevil I have made a program on book store. It involves the use of single linked list. So can I contribute in c++ folder.

You can contribute it to DSA folder and name as "singlelinkedlist.cpp" or something like that. Also put question above the code in that file for understanding.

**Comment by Aryan779** [comment]
ok, thank you

**Comment by KarandeepSingh15** [comment]
Hey @Astrodevil 
I want to add some more basic programs in C++. Can you assign it to me?

**Comment by Astrodevil** [comment]
> Hey @Astrodevil 
> 
> I want to add some more basic programs in C++. Can you assign it to me?

Go Ahead

**Comment by UKS28** [comment]
Hello @Astrodevil 

I want to add some concepts related to OOPS and DSA .Can you assign it to me?

**Comment by Astrodevil** [comment]
> Hello @Astrodevil 
> 
> 
> 
> I want to add some concepts related to OOPS and DSA .Can you assign it to me?

**Go ahead** 🚀 Make sure to follow folder patterns. Don't add same programs which are already there 👍🏻

Check carefully before making a PR!

**Comment by Aayush0606** [comment]
I want to add some C++ code , should I raise new issue?

**Comment by Astrodevil** [comment]
> I want to add some C++ code , should I raise new issue?
> 
> 

Not needed, but if you want to add some specific programs, better raise a issue.

**Comment by Aayush0606** [comment]
I will be adding folders in C++ folder about specific programs if that's ok?

**Comment by Astrodevil** [comment]
> 
> 
> I will be adding folders in C++ folder about specific programs if that's ok?

Ok, Go Ahead! If program is of DSA topics put it in DSA folder.

**Comment by Astrodevil** [comment]
Please raise a new issue and provide description of changes you want to make.

**Comment by samyaksand** [comment]
Hello, can you assign me this issue. I want to contribute some dsa solutions that I did while learning Data structures

**Comment by Astrodevil** [comment]
@samyaksand please raise a new issue and mention what you want to contribute, I will assign that

**Comment by Aman7445** [comment]
hey can i contribute some of the codes of my own?

**Comment by Ishika0-0** [comment]
Can I create some array operations like multiplication of 2D array 
Please assign this to me @Astrodevil
