### ISSUE TITLE
A new python project for hacktober fest 2021

### ISSUE THREAD

**Issue by nitinkumar30** [Astrodevil/Programming-Basics#40]
Under python, some projects need to be there which are helpful to many. 

I'd like to add a project related to Cyber Security which'll help people to communicate easily. This is a real issue in this **internet** world now which is the fastest-growing cyber hub today. I think I can provide a better solution to our communication by encrypting the message you want to transmit.

I've thought of other alternatives too like encrypting to an algorithm but they can be tracked & decrypted by various means. But if what if we encrypt our message into a media file? 

I'd like to include a pull request also for the same after the code being implemented in my local PC.

Please accept this issue under **_Hacktober fest 2021_**.

**Comment by saisumanthkumar** [comment]
I have a whatsapp automation python project can i add them

**Comment by Astrodevil** [comment]
@nitin30kumar Go ahead! Also Add proper docs and details about that project. Put whole one project related files under 1 folder

**Comment by Astrodevil** [comment]
> 
> 
> I have a whatsapp automation python project can i add them

create new issue for that

**Comment by saisumanthkumar** [comment]
ok @Astrodevil
