### ISSUE TITLE
More C++ Programs(CountDigitsAndReverseNumber,Foreachloop,TryCatch )

### ISSUE THREAD

**Issue by KarandeepSingh15** [Astrodevil/Programming-Basics#42]
@Astrodevil I want to add the stated programs in C++ for Hacktoberfest. Kindly Assign this to me

**Comment by Astrodevil** [comment]
@KarandeepSingh15 please provide more details.

**Comment by KarandeepSingh15** [comment]
> @KarandeepSingh15 Yes You can do that, just take care about repeating same files/kind of programs.

Yes, I have seen that programs related to CountDigitsAndReverseNumber are already covered by another contributor. Thus I will work on the other two
