### ISSUE TITLE
Want to add some cool small/basic Python Projects.

### ISSUE THREAD

**Issue by ssahibsingh** [Astrodevil/Programming-Basics#52]
I want to add some cool small/basic Python projects like checking internet speed with python, shutdown your computer using python and some more like them

**Comment by Astrodevil** [comment]
OK @ssahibsingh Make separate folder with your project name inside  Python>Projects folder

**Comment by Astrodevil** [comment]
Link PR here if made

**Comment by ssahibsingh** [comment]
@Astrodevil I don't know how to link PR to an issue. Could you please guide me?

**Comment by Astrodevil** [comment]
Check #no. In title of your issue and write here. I will find and merge 👍🏻 no problem

**Comment by ssahibsingh** [comment]
#298 Added Basic Python Projects

> Check #no. In title of your issue and write here. I will find and merge 👍🏻 no problem

Thank You😊
