### ISSUE TITLE
Want to add prime number code in python

### ISSUE THREAD

**Issue by riteshshukla04** [Astrodevil/Programming-Basics#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Astrodevil** [comment]
please edit description. and check python folder if same code is not there create one.

**Comment by shubhamnag14** [comment]
Can I add a prime number code in python..please assign me this

**Comment by Anjani87** [comment]
please assigne me this issue i can solve this is issue accordingly i am a good programmer in python language and recently i am pursuing b tech in computer science engeneering branch . (2 year) AND I HAVE RECENTLY COMPLETED A PAID TRAINNING COURSE FROM HACKERRANK IN PYTHON.
