### ISSUE TITLE
Want to add some medium level Projects (Python).

### ISSUE THREAD

**Issue by ssahibsingh** [Astrodevil/Programming-Basics#58]
I want to add some basic to medium level projects like automatic selfie on smile etc.

**Comment by Astrodevil** [comment]
@ssahibsingh go ahead

**Comment by shubhamnag14** [comment]
I want to add some basic to medium level projects like Qrgenerator and many more

**Comment by Astrodevil** [comment]
Link PR here if made

**Comment by shubhamnag14** [comment]
https://github.com/abhishekdoifode1/Hacktoberfest2021/pull/643

**Comment by Astrodevil** [comment]
@shubhamnag14 ? you mentioned pull request of someone else repo. Any reason?

**Comment by shubhamnag14** [comment]
#198
