### ISSUE TITLE
Want to add some cool Advance Projects (Python).

### ISSUE THREAD

**Issue by ssahibsingh** [Astrodevil/Programming-Basics#59]
I want to add cool advance projects like maze solver using python, Weather update using python.

**Comment by Astrodevil** [comment]
> 
> 
> I want to add cool advance projects like maze solver using python, Weather update using python.
Can you mention? Project name or any details.

**Comment by ssahibsingh** [comment]
I have already mentioned name of Projects. Projects like Maze Solver, Weather Update etc. These projects will not be of very advanced level but rather medium to advance level.

**Comment by Astrodevil** [comment]
Ok go ahead, put it in python/project directory

**Comment by Anjani87** [comment]
please assigne me this issue i can solve this is issue accordingly i am a good programmer in python language and recently i am pursuing b tech in computer science engeneering branch . (2 year) AND I HAVE RECENTLY COMPLETED A PAID TRAINNING COURSE FROM HACKERRANK IN PYTHON.

**Comment by Astrodevil** [comment]
@Anjani87 Create new issue for the work you want to do in this repository. This work is already assigned.

**Comment by Astrodevil** [comment]
@ssahibsingh Link PR here if made
