### ISSUE TITLE
Want to add Python program

### ISSUE THREAD

**Issue by ManasviGoyal** [Astrodevil/Programming-Basics#74]
@Astrodevil please assign me

**Comment by Astrodevil** [comment]
Please provide proper details In pr and mention this issue

**Comment by shubhamnag14** [comment]
i would to work in this issue

**Comment by Astrodevil** [comment]
@shubhamnag14 work on other issue by creating one.

**Comment by shubhamnag14** [comment]
i have created one issue..now can i do this work
