### ISSUE TITLE
Want to add array implementation in C (traversal, insertion, deletion)

### ISSUE THREAD

**Issue by nitinkumar30** [Astrodevil/Programming-Basics#98]
I cannot see any array implementation in the C language. I'm bothered about the new programmers who'd like to go through the basics of DSA. 

So, I want to contribute to the DSA in C language with array implementation which includes traversal, insertion & deletion.

I've considered another language (most probably Python) for DSA but we can completely do DSA in python with List &  Dictionary which have their own built-in methods. So moved to C language.

Please consider this request under 'Hacktober fest 2021'.

**Comment by Astrodevil** [comment]
> I cannot see any array implementation in the C language. I'm bothered about the new programmers who'd like to go through the basics of DSA. 
> 
> 
> 
> So, I want to contribute to the DSA in C language with array implementation which includes traversal, insertion & deletion.
> 
> 
> 
> I've considered another language (most probably Python) for DSA but we can completely do DSA in python with List &  Dictionary which have their own built-in methods. So moved to C language.
> 
> 
> 
> Please consider this request under 'Hacktober fest 2021'.
> 
> 

You can add the same in DSA folder and make more folders accordingly, Go ahead 👍🏻

**Comment by Astrodevil** [comment]
Link PR here if made
