### ISSUE TITLE
Add A* algorithm in python

### ISSUE THREAD

**Issue by shubhamnag14** [Astrodevil/Programming-Basics#99]
The A* algorithm is one of the most effective path finding algorithms used to find the shortest path between two points

**Comment by Astrodevil** [comment]
Go ahead🚀

**Comment by shivanisorte** [comment]
Please assign to me

**Comment by Astrodevil** [comment]
@shubhamnag14 Do you still want to work on this?

**Comment by shubhamnag14** [comment]
i have made on this PR..kindly check it..do the needful

**Comment by Astrodevil** [comment]
mention PR no.

**Comment by shubhamnag14** [comment]
#199
